// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcG3QKEMGdkB4wvydfdSNke3WYveOf_6c',
    appId: '1:637016744812:web:b297ac0822cac318ca8949',
    messagingSenderId: '637016744812',
    projectId: 'halotani-2bf84',
    authDomain: 'halotani-2bf84.firebaseapp.com',
    databaseURL: 'https://halotani-2bf84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'halotani-2bf84.appspot.com',
    measurementId: 'G-2TR6KRNP9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAomzvLY0dhZbgQncpKpKqbZ5O6v-tyIQ',
    appId: '1:637016744812:android:df7b14995b09dadfca8949',
    messagingSenderId: '637016744812',
    projectId: 'halotani-2bf84',
    databaseURL: 'https://halotani-2bf84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'halotani-2bf84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZ5uc8PpFRCc1DyoxpjtR_1zIadwcMAM',
    appId: '1:637016744812:ios:e7ed4860f37f18f2ca8949',
    messagingSenderId: '637016744812',
    projectId: 'halotani-2bf84',
    databaseURL: 'https://halotani-2bf84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'halotani-2bf84.appspot.com',
    iosBundleId: 'com.example.halotani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZ5uc8PpFRCc1DyoxpjtR_1zIadwcMAM',
    appId: '1:637016744812:ios:e7ed4860f37f18f2ca8949',
    messagingSenderId: '637016744812',
    projectId: 'halotani-2bf84',
    databaseURL: 'https://halotani-2bf84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'halotani-2bf84.appspot.com',
    iosBundleId: 'com.example.halotani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcG3QKEMGdkB4wvydfdSNke3WYveOf_6c',
    appId: '1:637016744812:web:5c8bf70de51a4f67ca8949',
    messagingSenderId: '637016744812',
    projectId: 'halotani-2bf84',
    authDomain: 'halotani-2bf84.firebaseapp.com',
    databaseURL: 'https://halotani-2bf84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'halotani-2bf84.appspot.com',
    measurementId: 'G-90F3VXYTSM',
  );
}
